name: Test

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:

    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2

      - name: Install ksh, zsh, shellcheck
        run: sudo apt-get install -qq ksh zsh shellcheck

      - name: Print Tool Versions
        run: |
          bash --version
          ksh --version || true
          zsh --version
          shellcheck --version

      - name: Run make check
        run: make check
